namespace Test
{
    enum TypeAttributeEnum
    {
        Alpha,
        Red,
        Green,
        Blue
    };

    [attributeusage(target_interface)]
    [version(1)]
    attribute TypeAttribute
    {
        // These are the only types that MIDL appears to support for attributes.

        Boolean Bools;
        Int32 Integers;
        String Strings;
        type Types;
        TypeAttributeEnum Enums;
    };

    struct TypeStruct
    {
        Boolean B;
        Char C;
        UInt8 U8;
        Int16 I16;
        UInt16 U16;
        Int32 I32;
        UInt32 U32;
        Int64 I64;
        UInt64 U64;
        Single F32;
        Double F64;
        String S;
    };

    [Type(FALSE, 321, "Hello world", TypeStruct, TypeAttributeEnum.Blue)]
    interface ITypeAttribute
    {
        void Call();
    };
}
